// ============================================================
// SEO Ranking Skill Constants & Registry
// Sourced directly from seo-ranking-skill/skills/seo-ranking/
// ============================================================

export const CANONICAL_ISSUE_TYPES = [
  'intent_mismatch',
  'main_question_unanswered',
  'thin_coverage',
  'missing_subtopic',
  'low_information_gain',
  'lacking_specificity',
  'unoriginal_content',
  'unsupported_claim',
  'fabricated_data',
  'fake_experience',
  'weak_eeat_transparency',
  'poor_readability',
  'missing_title',
  'weak_title',
  'duplicate_title',
  'missing_h1',
  'multiple_h1',
  'missing_meta_description',
  'weak_meta_description',
  'duplicate_meta_description',
  'poor_slug',
  'keyword_missing_naturally',
  'keyword_stuffing',
  'semantic_gap',
  'weak_headings',
  'missing_internal_links',
  'weak_anchor_text',
  'missing_external_sources',
  'image_not_useful',
  'missing_alt_text',
  'stuffed_alt_text',
  'schema_missing',
  'schema_type_mismatch',
  'invalid_schema',
  'fabricated_schema_property',
  'canonical_missing',
  'canonical_conflict',
  'og_missing',
  'noindex_unintended',
  'sitemap_missing_page',
  'duplicate_url',
  'broken_link',
  'redirect_chain',
  'mobile_issue',
  'cwv_issue',
  'no_direct_answer',
  'unclear_entities',
  'factual_ambiguity',
  'weak_structure_for_ai',
  'no_unique_information',
  'cannibalization_high',
  'cannibalization_medium',
  'cannibalization_low',
  'outdated_content',
  'intent_drift',
  'weak_title_meta_refresh',
] as const;

// 9 Categories & Default Weights for SEO Content Score (SCORING.md)
export const CONTENT_SCORE_CATEGORIES = [
  { name: 'Search Intent Alignment', weight: 12, checks: ['SEO-V01', 'SEO-V02'] },
  { name: 'Content Quality & E-E-A-T', weight: 14, checks: ['SEO-V06', 'SEO-V07', 'SEO-V08', 'SEO-V09', 'SEO-V10', 'SEO-V11', 'SEO-V12'] },
  { name: 'Topic Coverage', weight: 12, checks: ['SEO-V03', 'SEO-V04', 'SEO-V20'] },
  { name: 'Information Gain', weight: 12, checks: ['SEO-V05', 'SEO-V07', 'SEO-V40'] },
  { name: 'On-Page SEO', weight: 22, checks: ['SEO-V13', 'SEO-V14', 'SEO-V15', 'SEO-V16', 'SEO-V17', 'SEO-V18', 'SEO-V19', 'SEO-V21', 'SEO-V29', 'SEO-V30'] },
  { name: 'Internal Linking', weight: 8, checks: ['SEO-V22', 'SEO-V23'] },
  { name: 'Image SEO', weight: 6, checks: ['SEO-V25', 'SEO-V26'] },
  { name: 'Structured Data', weight: 8, checks: ['SEO-V27', 'SEO-V28'] },
  { name: 'AI Search Readiness', weight: 6, checks: ['SEO-V36', 'SEO-V37', 'SEO-V38', 'SEO-V39'] },
] as const;
